<?php
/**
 * @wordpress-plugin
 * Plugin Name:       LTI
 * Description:       IMS LTI Integration for Wordpress
 * Version:           0.1
 * Author:            Jeff Graham
 * Author URI:        http://funnymonkey.com
 * Text Domain:       lti
 * License:           MIT
 * GitHub Plugin URI: https://github.com/lumenlearning/lti
 */

/**
 * @todo move this to its own repo
 * @todo update licensing details and other plugin meta.
 * @todo Add check to LTI::generateToken() to ensure tokens are unique. Probably
 *       need to split to two separate functions one for keys and one for
 *       secrets. Those should be unique across all lti_consumer posts.
 * @todo Request LTI credentials UI (skip standard post UI) nothing should be
 *       user editable. Adjust settings in call to register_post_type()
 *       currently it intentionally allows editing to aid in debugging.
 * @todo Enable users to creat/view/delete their own lti_consumer posts, but not
 *       anyone other user's lti_consumer posts. Admins should be able to see
 *       delete any credentials, and to create credentials on behalf of another
 *       user. Maybe expose normal UI with author selection for admin, but only
 *       on create. We likely don't want to enable "transferring" of credentials
 * @todo refactor add_meta_box() callbacks to not display key/secret when
 *       adding.
 * @todo fix view templates & add enough user prompting & inline documentation
 *       on how to use the LTI information. Make this pluggable so that it is
 *       easy for people to add site-specific & LMS-specific details via
 *       templating to facilitate easy overrides and straightforward pull
 *       requests
 * @todo Consider draft->published workflow for lti_consumer posts. Where draft
 *       would indicate inactive or unapproved credentials, and published
 *       indicating the credentials are active.
 */

// If file is called directly, abort.
if ( ! defined( 'ABSPATH' ) ) exit;

// Length of token generated by OAuthProvider::generateToken()
define ('LTI_OAUTH_TOKEN_LENGTH', 40);

// Constants for our meta field names
define('LTI_META_KEY_NAME', '_lti_consumer_key');
define('LTI_META_SECRET_NAME', '_lti_consumer_secret');

// Do our necessary plugin setup and add_action routines.
LTI::init();

class LTI {
  public static function init() {
    if ( !defined( 'LTI_PLUGIN_DIR' ) ) {
      define( 'LTI_PLUGIN_DIR', __DIR__ . '/' );
    }

    if ( ! defined( 'LTI_PLUGIN_URL' ) ) {
      define( 'LTI_PLUGIN_URL', plugin_dir_url( __FILE__ ) );
    }

    add_action( 'init', array( __CLASS__, 'register_post_type' ) );
    add_action( 'add_meta_boxes', array( __CLASS__, 'add_meta_boxes' ) );
    add_action( 'save_post', array( __CLASS__, 'save') );
    add_action( 'admin_notices', array( __CLASS__, 'check_dependencies') );

		if ( is_admin() ) {
			add_action('admin_menu', array( __CLASS__, 'admin_menu' ) );
		}
	}

  public static function admin_menu () {
    add_options_page('LTI', 'LTI', 'manage_options', 'lti_options', array( __CLASS__, 'plugin_settings_page'));
  }

  public static function plugin_settings_page() {
    if ( ! current_user_can('manage_options') ) {
      wp_die( __('You do not have sufficient permissions to access this page.') );
    }
    include(LTI_PLUGIN_DIR . 'settings.php');
  }

  /**
   * Check dependencies
   */
  public static function check_dependencies() {
    if ( ! extension_loaded('oauth') ) {
      echo '<div id="message" class="error fade"><p>';
      echo 'LTI integration requires the OpenAuth library. Please see <a href="php.net/manual/en/book.oauth.php">oauth</a> for more information.';
      echo '</p></div>';
    }
  }

  /**
   * Register our custom post type to track LTI consumers.
   *
   * @see http://codex.wordpress.org/Function_Reference/register_post_type
   */
  public static function register_post_type() {
    $args = array(
      'labels' => array(
        'name' => __( 'LTI Consumers' ),
        'add_new' => _x('Add New', 'lti_consumer' ),
        'singular_name' => __( 'LTI Consumer' ),
        'add_new_item' => __( 'Add New LTI Consumer' ),
        'edit_item' => __( 'Edit LTI Consumer' ),
        'new_item' => __( 'New LTI Consumer' ),
        'view_item' => __( 'View LTI Consumer' ),
        'search_items' => __( 'Search LTI Consumers' ),
        'not_found' => __( 'No LTI Consumers found' ),
        'not_found_in_trash' => ( 'No LTI Consumers found in trash' ),
      ),
      'description' => 'LTI consumer credential information',
      'public' => true,
      'rewrite' => true,
      'can_export' => false,
      'supports' => array(
        'author',
      ),
    );
    register_post_type( 'lti_consumer', $args );
  }

  /**
   * Attach custom meta fields.
   *
   * @see http://codex.wordpress.org/Function_Reference/add_meta_box
   */
  public static function add_meta_boxes() {
    add_meta_box('consumer_secret', 'Consumer Secret', array( __CLASS__, 'consumer_secret_meta'), 'lti_consumer', 'normal' );
    add_meta_box('consumer_key', 'Consumer Key', array( __CLASS__, 'consumer_key_meta'), 'lti_consumer', 'normal' );
  }

  /**
   * Callback for add_meta_box().
   *
   * @see http://codex.wordpress.org/Function_Reference/add_meta_box
   */
  public static function consumer_secret_meta( $post ) {
    // Add a nonce field so we can check for it later.
    wp_nonce_field( 'lti_consumer', 'lti_consumer_nonce');

    // Use get_post_meta to retrieve an existing value from the database.
    $secret = get_post_meta( $post->ID, LTI_META_SECRET_NAME, true);

    if ( empty($secret) ) {
      $secret = LTI::generateToken();
    }

    // Display the form, using the current value.
    echo '<label for="lti_consumer_secret">';
    _e( 'Consumer secret used for signing LTI requests.' );
    echo '</label>';
    echo '<input type="text" id="lti_consumer_secret" name="lti_consumer_secret"';
    if ( ! is_admin() ) {
      echo ' disabled="disabled"';
    }
    echo ' value="' . esc_attr( $secret ) . '" size="40" />';

  }

  /**
   * Callback for add_meta_box().
   *
   * @see http://codex.wordpress.org/Function_Reference/add_meta_box
   */
  public static function consumer_key_meta( $post ) {
      // Use get_post_meta to retrieve an existing value from the database.
    $key = get_post_meta( $post->ID, LTI_META_KEY_NAME, true);

    if ( empty( $key ) ) {
      $key = LTI::generateToken();
    }

    // Display the form, using the current value.
    echo '<label for="lti_consumer_key">';
    _e( 'Consumer key used for signing LTI requests.' );
    echo '</label>';
    echo '<input type="text" id="lti_consumer_key" name="lti_consumer_key"';
    if ( ! is_admin() ) {
      echo ' disabled="disabled"';
    }
    echo ' value="' . esc_attr( $key ) . '" size="40" />';

  }

  /**
   * Create a new post.
   *
   * lti_consumer posts really have no user editable data so this helps by
   * managing all the programmatic pieces so we can just pass the $author_id the
   * post should be created on behalf of.
   */
  public static function create( $author_id = NULL ) {
    // default to current user (or admin) if none provided
    if ( $author_id == NULL ) {
      $user = wp_get_current_user();
      if ( 0 == $user->ID ) {
        // User is not logged in, refuse to create
        return FALSE;
      }
    }
    else {
      $user = get_userdata( $author_id );
    }

    $post = array(
      'post_content'          => '',
      'post_name'             => '',
      'post_title'            => 'LTI: ' . $user->display_name,
      'post_status'           => 'private',
      'post_type'             => 'lti_consumer',
      'post_author'           => $user->ID,
      'ping_status'           => 'closed',
      'post_password'         => '',
      'post_excerpt'          => '',
      'import_id'             => '',
      'comment_status'        => 'closed',
    );
    $post_id = wp_insert_post($post, false);

    // Now attach our key/secret metadata
    if ( ! empty($post_id) ) {
      update_post_meta($post_id, LTI_META_KEY_NAME, LTI::generateToken());
      update_post_meta($post_id, LTI_META_SECRET_NAME, LTI::generateToken());
    }
  }

  /**
   * Create a new random token
   *
   * We pass through sha1() to return a 40 character token.
   */
  public static function generateToken() {
    $token = OAuthProvider::generateToken(LTI_OAUTH_TOKEN_LENGTH);
    return sha1($token);
  }

  /**
   * Save a post submitted via form.
   *
   * This is here for completeness, but likely needs review to see if we want to
   * expose this part of the UI workflow at all.
   */
  public static function save( $post_id ) {
    // Check if our nonce is set
    if ( ! isset( $_POST['lti_consumer_nonce'] ) ) {
      return $post_id;
    }

    $nonce = $_POST['lti_consumer_nonce'];

    // Verify the nonce is valid
    if ( ! wp_verify_nonce($nonce, 'lti_consumer' ) ) {
      return $post_id;
    }

    if ( defined( 'DOING AUTOSAVE' ) && DOING_AUTOSAVE ) {
      return $post_id;
    }

    if ( 'lti_consumer' == $_POST['post_type']['lti_consumer'] ) {
      if ( ! current_user_can( 'edit_page', $post_id) ) {
        return $post_id;
      }
    }
    else {
      if ( ! current_user_can( 'edit_post', $post_id) ) {
        return $post_id;
      }
    }

    // Save to save data now
    update_post_meta( $post_id, LTI_META_KEY_NAME, $_POST['lti_consumer_key'] );
    update_post_meta( $post_id, LTI_META_SECRET_NAME, $_POST['lti_consumer_secret'] );
  }
}

